inc:
  # Blog Information
  title:        "SDSLabs Blog"
  subtitle:     "Innovating at IIT Roorkee"
  cover_image:  cover.jpg
  logo:         logo.png

  # Company information
  company:      SDSLabs
  url:          http://sdslabs.co/
  github:       sdslabs
  facebook:     sdslabs
  twitter:      sdslabs
  gplus:        '101733513430697982016'
  team_link:    http://team.sdslabs.co/

  # Product Information
  product_link: http://sdslabs.co.in/
  tagline:      "Innovating at IIT Roorkee"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         true


 # Analytics
  analytics:
    google:
      # eg. 'UA-123-12'
      id:       false


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://blog.sdslabs.co
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: false
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:      /:year/:month/:title
paginate_path: 'page:num'
paginate: 10

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

# maruku:
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex

# rdiscount:
#   extensions: []

# redcarpet:
#   extensions: []

# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   use_coderay: false

#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

# redcloth:
#   hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
# assets:

#   dirname: assets
#   baseurl: /assets/
#   sources:
#     - _assets/javascripts
#     - _assets/stylesheets
#     - _assets/images
#   js_compressor: uglifier
#   css_compressor: sass
#   cachebust: none
#   cache: false
#   gzip: [ text/css, application/javascript ]
#   debug: false